#!/bin/bash

partition="gpu,fas_gpu,gpu_requeue"  # which partitions to request time on
# Need to keep a tunnel open if going to run Jupyter notebooks
port=8987  # Which port to tunnel through.
time=2  # how many hours to request for 
mem=8000  # Memory in MB
n=1  # How many GPUs to request

# The abbreviated name of the script running
BASENAME="interact_gpu"

# Standard function to print an error and exit with a failing return code
error_exit () {
    echo "${BASENAME} - ${1}" >&2
    exit 1
}

# Usage info
show_help() {
error_exit "
Usage: ${BASENAME} [-h] [-p gpu_requeue,fas_gpu,gpu_requeue] [-t 2] [--port 8987] [-m 8000] [-n 1]
Submit a SLURM request for an interactive session, with a GPU available. A port (specified by --port) will be available for tunneling.

     -h / --help       display this help and exit
     -p / --partition  which partition to submit to (default: gpu_requeue)
     -t / --time       time (in hours) to request for (default: 2)
     --port            which port to use to tunnel (default: 8987)
     -m / --mem        how much memory (in MB) to request (default: 4000)
     -n / --ngpu       how many GPUs to request (default: 1)
"
}

while [ "$1" != "" ]; do
    case $1 in
	# display usage synopsis, then exit
	-h|-\?|--help )
	    show_help
	    ;;
	# set the requested partition
	-p|--partition )
	    partition=$2
	    shift
	    ;;
	# set the requested time
	-t|--time )
	    time=$2
	    shift
	    ;;
	# set the requested tunnel port
	--port )
	    port=$2
	    shift
	    ;;
	# set the requested memory
	-m|--mem )
	    mem=$2
	    shift
	    ;;
	# set the requested GPU number
	-n|--ngpu )
	    n=$2
	    shift
	    ;;
    esac
    shift
done

echo "requesting $mem MB memory and 1 GPU on partition $partition for $time hours, tunneling to $port"
srun --pty --mem $mem -n 1 --gres=gpu:$n -p $partition -t 0-$time:00 --tunnel $port:$port bash
